---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(hrbrthemes)
theme_set(theme_minimal())
```

```{r}
plot_ics = function(d) {
    d %>%
        ggplot(aes(
            ymin = low,
            y = mid,
            ymax = high,
            x = metodo
        )) +
        geom_linerange() +
        geom_point(color = "coral", size = 3) +
        scale_y_continuous(limits = c(-1, 1)) +
        labs(x = "", y = "Diferença na precisão (novo - atual)") +
        coord_flip()
}
```

```{r}
tribble(
    ~metodo, ~low, ~mid, ~high, 
    "C1", .35, .45, .55, 
    "C2", -.65, -.5, -.35) %>% 
    plot_ics()
```

```{r}
tribble(
    ~metodo, ~low, ~mid, ~high, 
    "C1", -.65, -.55, -.45, 
    "C2", -.5, -.1, .35, 
    "C3", -.93, -.44, .18, 
    "C4", -.1, 0, .1
    ) %>% 
    plot_ics()
```

```{r}
tribble(
    ~metodo, ~low, ~mid, ~high, 
    "C5", .05, .1, .15, 
    "C6", -.07, .01, .08, 
    "C7", -.4, .1, .6 
    ) %>% 
    plot_ics()
```


```{r}
tribble(
    ~metodo, ~low, ~mid, ~high, 
    "C1", -1, -.9, -.8, 
    "C2", -.6, -.45, -.3, 
    "C3", -.4, -.1, .2, 
    "C4", -.5, 0.05, .5, 
    "C5", -.07, -.02, .03, 
) %>% 
    plot_ics()

```

